### PR TITLE
Allow blocks with zero transactions

### PR DESCRIPTION
**Pull request by ftheirs**
If the class tree from the chain is not initialized yet (class_commitment = Felt::Zero), Pathfinder will deliver that field with a None. This situation was handled.
Besides, the previous and current root hash from the class tree was taken from the storage proofs since they will be present always. Previous approach relied on class proof but in order to get them, it was necessary to have transactions in both blocks. Therefore, this PR allows SNOS to process blocks with zero transactions.

Replacing: https://github.com/keep-starknet-strange/snos/pull/418

Issue Number: N/A

## Type

- [x] feature
- [x] bugfix
- [ ] dev (no functional changes, no API changes)
- [ ] fmt (formatting, renaming)
- [ ] build
- [ ] docs
- [ ] testing

## Breaking changes?

- [ ] yes
- [x] no

### CODE REVIEW

**Review by HermanObst — APPROVED** [review]
LGTM

**Review by GMKrieger — APPROVED** [review]
LGTM

**Review by whichqua — APPROVED** [review]
LGTM

**Review by notlesh — APPROVED** [review]

**Comment by shamsasari** [comment]
Shouldn't this PR have been merged by now? It was approved over a week ago.

**Pull request merged**
