### PR TITLE
Moved compiled snos import to allowing using snos as a dependency

### PR DESCRIPTION
**Pull request by matzayonc**
Issue Number: N/A

## Type

- [ ] feature
- [x] bugfix
- [ ] dev (no functional changes, no API changes)
- [ ] fmt (formatting, renaming)
- [ ] build
- [ ] docs
- [ ] testing

## Description
I moved the include_bytes!() with snos import to tests and binary, because it is not present when used as a dependency.

## Breaking changes?

- [x] yes
- [ ] no

### CODE REVIEW

**Review by notlesh — APPROVED** [review]

**Review by HermanObst — APPROVED** [review]
Looking good! Thanks @matzayonc

**Review by HermanObst — CHANGES_REQUESTED** [review]
@matzayonc plase fix clippy and formatter so the CI can run :) 
Otherwise code seems good!

**Comment by matzayonc** [comment]
Thanks, I'm already using it as a dependency and it works perfectly fine now!

**Review by HermanObst — APPROVED** [review]
LGTM

**Pull request merged**
