### PR TITLE
Feature: ASSIGN_BYTECODE_SEGMENTS hint

### PR DESCRIPTION
**Pull request by odesenfans**
Issue Number: N/A

## Type

- [x] feature
- [ ] bugfix
- [ ] dev (no functional changes, no API changes)
- [ ] fmt (formatting, renaming)
- [ ] build
- [ ] docs
- [ ] testing

## Breaking changes?

- [ ] yes
- [x] no

### CODE REVIEW

**Comment by maciejka** [comment]
Hints related to selective bytecode loading can be similarly to SECP related hints left for later. It is an optimisation that os may or might not do. Not on critical path.

**Comment by odesenfans** [comment]
> Hints related to selective bytecode loading can be similarly to SECP related hints left for later. It is an optimisation that os may or might not do. Not on critical path.

Yes I realized that a bit late. Oh well, it's implemented at least.

**Comment by notlesh** [comment]
> > Looks ok, but something this complex really needs a test. There is at least one more bytecode related hint, btw.
> 
> Is this really complex enough? It's pretty trivial IMO, we just extract one field from a struct and turn it into an iterator. I can add tests if you insist.

The code here isn't, but the overall mechanism is, example: https://github.com/starkware-libs/cairo-lang/blame/master/src/starkware/starknet/core/os/contract_class/compiled_class.cairo#L118

But as @maciejka pointed out, it's not in critical path, so I suggest either close it or merge it for now, up to you.

**Review by notlesh — APPROVED** [review]

**Comment by odesenfans** [comment]
> The code here isn't, but the overall mechanism is, example: https://github.com/starkware-libs/cairo-lang/blame/master/src/starkware/starknet/core/os/contract_class/compiled_class.cairo#L118
> 
> But as @maciejka pointed out, it's not in critical path, so I suggest either close it or merge it for now, up to you.

Let's merge it, I don't see a reason not to.

**Pull request merged**
